# active spring boot profile
spring:
   profiles:
      # default: dev
      active: dev

---

# common - spring configuration
spring:
   # devtools - live reload
   devtools:
      livereload:
         enabled: true

   # mvc
   mvc:
      view:
         prefix: /WEB-INF/views/
         suffix: .jsp

   # message resource(Internationalization)
   messages:
      always-use-message-format: true
      basename: messages/messages_ko
      encoding: UTF-8

   # multipart
   servlet:
      multipart:
         enabled: true
         max-file-size: 50MB
         max-request-size: 50MB

   # aop(@EnableAspectJAutoProxy)
   aop:
      auto: true
      proxy-target-class: true

---

# dev profile - spring boot configuration
spring:
   config:
      activate:
         on-profile: dev

   # datasource
   datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://34.64.204.254:5432/yum?characterEncoding=utf8
      username: yum
      password: ant-yum
      hikari:
         minimum-idle: 10
         maximum-pool-size: 20

---

# production profile - spring boot configuration
spring:
   config:
      activate:
         on-profile: production

   # datasource
   datasource:
      username: yum
      password: yum?!@#yammi123
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://34.64.204.254:5432/yum?characterEncoding=utf8
      hikari:
         minimum-idle: 100
         maximum-pool-size: 200

# server
server:
   port: 8080
   servlet:
      context-path: /yum
   encoding:
      charset: utf-8
      enabed: true
      force: false
      force-request: false
      force-response: false

---

# mybatis
mybatis:
   config-location: classpath:mybatis/configuration.xml

---

# logging
logging:
   config: classpath:logback.xml